name: Hot Interconnects
email: info@hoti.org
description: The international forum where the high-performance computing and high-speed networking communities meet
baseurl: "/2025"
url: "https://hoti.org"

twitter:
  username: IEEEHOTI
facebook:
  username: hoti.org

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"

logo: /assets/img/hoti_logo_150x75.png

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single # TODO: change from splash to single after adding sponsor sidebar
      # Wide might not work with hacked layouts (I see the sponsor sidebar jump from right to left)
      sidebar: sponsors-sidebar.md #from the _includes folder
      # Build settings

slack-workspace-url: https://hot-interconnects.slack.com/

exclude:
  - _ignore
  - proceedings.md

destination: hoti.org/2025

plugins:
  - jekyll-target-blank
